name: Run Azure and launch TF workflow
on: [push]

permissions:
      id-token: write
      contents: read

env:
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_AD_CLIENT_SECRET }}"

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - run: ls -lha1

    - run: terraform init

    - id: apply
      run: terraform apply -auto-approve

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}